authorname: "Lasai Barreñada"
draft: false

project:
  type: website
  
  resources:
    - "img/**"
    - "_redirects"
    - "speaking/pdf/**"

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

title-meta: "Lasai Barreñada"
description-meta: "Bio-statistician | PhD researcher | Prediction models, Healthcare, Research"

website:
  title: "Lasai Barreñada"
  description: "Bio-statistician | PhD researcher | Prediction models, Healthcare, Research"
  site-url: https://lasaibarrenada.github.io/
  image: img/website_thumbnail.png
  
  repo-url: "https://github.com/LasaiBarrenada/LasaiBarrenada.github.io/"
  repo-branch: main
  
  search: false
  
  navbar:
    pinned: true
    logo: /img/lb_logo_opt1.svg
    left:
      - text: Projects
        href: projects/projects-page.qmd
      - text: Talks
        href: speaking/speaking-page.qmd
      - text: CV
        href: cv/cv-page.qmd
      - text: Publications
        href: Publications/publications-page.qmd
      - text: Software
        href: software/software-page.qmd
    right:
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=uPOL3NkAAAAJ&hl=en
        target: _blank
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0001-8020-0210
        target: _blank
      - text: "{{< ai researcherid >}}"   # Academicons (Web of Science)
        href: https://www.webofscience.com/wos/author/record/ACY-2331-2022
        target: _blank
      - icon: twitter # Font Awesome (Built-in)
        href: https://bsky.app/profile/lasaibarrenada.bsky.social
        target: _blank
      - text: "{{< fa brands github >}}"  # Font Awesome (Built-in)
        href: https://github.com/LasaiBarrenada
        target: _blank
      - text: "{{< ai osf >}}"
        href: https://osf.io/pgkjv/
        target: _blank
      - text: "{{< fa brands linkedin >}}"# Font Awesome (Built-in)
        href: https://www.linkedin.com/in/lasaib/
        target: _blank
      - icon: envelope
        aria-label: email
        href: "mailto:lasai.barrenadataleb@kuleuven.be"
  
  favicon: img/favicon.svg
  
  twitter-card: 
    creator: "@BarrenadaLasai"
    image: "/img/website_thumbnail.png"
    
  open-graph: 
    image: "/img/website_thumbnail.png"
    locale: en_US
    
  google-analytics: 
    tracking-id: G-3X228H9QKP
    storage: cookies
  
  page-footer: 
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2026 Lasai Barreñada | Template by Marvin Schmitt </span>
      <span class="faux-block"><a href="https://github.com/LasaiBarrenada/LasaiBarrenada.github.io/">{{< fa brands github >}} Source Code</a></span>
    center: |
      <span class="faux-block"><a href="/license/index.html">License</a></span>
    right: |
      <span class="faux-block">Last updated: <script>document.write(new Date().toLocaleDateString('en-US',{month:'long',year:'numeric'}))</script></span>
      <span class="faux-block"> Built with <a href="https://quarto.org/">Quarto</a></span>
execute:
  freeze: true
  
filters:
  - html/newpagelink.lua
  - academicons

format:
  html:
    include-in-header: html/seo.html
    fontsize: 1.1em
    theme: 
      - flatly
      - html/styles.scss
    toc: false
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
