---
title: CV
format:
  quarto-cv-pdf: default
classoption: dvipsnames
author: 
  Lasai Barreñada
date: last-modified
address: "Herestraat 49, Leuven 3000, Belgium"
email: lasai.barrenadataleb@kuleuven.be
fontsize: 9pt
fontfamily: ebgaramond-maths 
geometry: "top=0.8cm, bottom=0.8cm, left=1.5cm, right=1.5cm" 
colorlinks: true
linkcolor: NavyBlue
urlcolor: NavyBlue
citecolor: NavyBlue
header-includes:
  - \usepackage{titlesec}
  - \titleformat{\section}{\normalfont\Large\bfseries\color{Maroon}}{}{0pt}{}
  - \titleformat{\subsection}{\normalfont\large\bfseries\color{Maroon}}{}{0pt}{}
orcid: 0000-0001-8020-0210
web: lasaibarrenada.github.io
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: peer_bib.bib
  other: other_bib.bib
validate-yaml: false
csl: nature.csl
profile: "Incoming FWO Postdoctoral Fellow in clinical prediction models at KU Leuven."
---

# Professional Experience

**KU Leuven**

FWO Postdoctoral Fellow (Leuven) \hfill 10/2026-10/2029 (Incoming)

PhD Researcher in clinical prediction models (Leuven) \hfill 10/2022-Current

**Memorial Sloan Kettering Cancer Center**

Visiting PhD Researcher (New York) \hfill 02/2025-06/2025

**Julius center - UMC Utrecht**

Visiting PhD Researcher (Utrecht) \hfill 10/2024-02/2025


**Basque Center for Applied Mathematics (BCAM)**

Research Technician in Machine Learning (Bilbao) \hfill 12/2021-09/2022

**Spanish National Statistical Office (INE Spain)**

Postgraduate Internship (Madrid) \hfill 10/2020-09/2021

<!-- **Publicis Media** -->

<!-- Data Science Internship (Madrid) \hfill 10/2019-05/2020 -->

# Education

**KU Leuven**, PhD in Biomedical Sciences \hfill 09/2022-09/2026 

**Complutense University of Madrid (UCM)**, European Master in Official Statistics (EMOS) \hfill 2019-2021

<!-- **University of Angers**, B.A. Marketing (Erasmus Programme) \hfill 2017-2018 -->

**University of Granada**, B.A. Marketing \hfill 2015-2019

# Publications

::: {#refs-peer}
:::

# Peer review

Conducted >30 peer reviews for **Statistics in Medicine**, **Ultrasound in Obstetrics and Gynecology**, **International Journal of Gynecological Cancer**, **Heliyon**, **npj precision oncology**, **Nature Communications medicine** and **Diagnostic and prognostic research**
<!-- # Technical Reports & Preprints -->

<!-- ::: {#refs-other} -->
<!-- ::: -->

# Conference Presentations

**Cost-based variable selection to improve clinical utility of prediction models (Poster)**, ISCB, Freiburg \hfill 10/2026


**Problem of Individual Risk Estimation for Health AI (Talk)**, SEB, Bilbao \hfill 01/2026

**Updating the ADNEX model for surgically and conservatively managed patients (Talk)**, ISUOG, Cancun \hfill 09/2025

**Combining calibration plots (Talk)**, MEMTAB, Birmingham \hfill 04/2025

**Problem of Individual Risk Estimation for Health AI (Talk)**, ENAR, New Orleans \hfill 03/2025

**Head-to-head comparisons of RMI and ADNEX models (Talk)**, ISUOG, Budapest \hfill 09/2024

**Multicenter flexible calibration curves using random effects (Poster)**, ISCB, Thessaloniki \hfill 07/2024

**Drawing multicenter calibration curves (Talk)**, SEB, Barcelona \hfill 02/2024

**ADNEX model systematic review and meta-analysis (Talk)**, ISUOG, Seoul \hfill 10/2023

**Do we understand random forests? (Poster)**, ISCB, Milan \hfill 08/2023

**Do we understand random forests? (Poster)**,YSM, Leicester \hfill 07/2023

# Awards & Prizes

**Young Investigator Award in Gynaecology**, issued by ISUOG \hfill 2023

**Young Statisticians Prize (YSP)**, 2\textsuperscript{nd}, issued by IAOS \hfill 2022

<!-- # Skills -->

<!-- - Clinical Prediction Models -->
<!-- - Meta-analysis -->
<!-- - Machine Learning -->
<!-- - Statistical Analysis -->
<!-- - Data Science -->
<!-- - Biomedical Research -->
<!-- - Programming: **R**, **Python** -->

# Professional Memberships

International Society of Ultrasound in Obstetrics and Gynecology (ISUOG), International Ovarian Tumour Analysis group (IOTA), International Biometric Society (IBS), International Society For Clinical Biostatistics (ISCB) 

# Fellowships

- [**STRATOS**](https://www.stratos-initiative.org/) early career adjunct member

- [**ISCB early career biostatistician**](https://iscb.international/early-career-biostatisticians/) committee

- **FEPS Young Academics Network** 10th cycle

# Grants

- FWO Postdoctoral Fellowship \hfill 2026-2029
- FWO travel grants x4 \hfill 2023,2024,2025,2026
- FWO long stay abroad grant (5 months) \hfill 2025-2026 

# Languages

- **Spanish**: Native
- **Basque**: Native
- **English**: Full Working Proficiency
- **French**: Full Working Proficiency

<!-- # References -->

<!-- Available upon request, though likely would include David Salgado, Ben Van Calster, Laure Wynants, Dirk Timmerman. -->
